name:                reimagined-fiesta
version:             0.1.0.0
github:              "githubuser/reimagined-fiesta"
license:             MIT
author:              "Christian Gill"
maintainer:          "gillchristiang@gmail.com"
copyright:           "2019 Christian Gill"

extra-source-files:
- readme.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/gillchristian/reimagined-fiesta#readme>

dependencies:
- base >= 4.7 && < 5
- aeson ^>= 1.4.2.0
- parsec ^>= 3.1.14.0
- parsec-numbers
- bytestring ^>= 0.10.8.2


library:
  source-dirs: src

executables:
  reimagined-fiesta-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reimagined-fiesta
    default-extensions: OverloadedStrings

tests:
  reimagined-fiesta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reimagined-fiesta
